name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install buildozer + deps
        run: |
          python -m pip install --upgrade pip
          pip install "cython<3.1" buildozer

      - name: Install system build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake libtool pkg-config build-essential unzip zip

      - name: Dummy buildozer warmup
        run: |
          buildozer android p4a -- version || true
          ls -R .
          echo "Warmup finished"
      
      - name: Upload placeholder
        uses: actions/upload-artifact@v4
        with:
          name: placeholder
          path: main.py
