name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install buildozer + deps
        run: |
          python -m pip install --upgrade pip
          pip install "cython<3.1" buildozer

      - name: Install system build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool pkg-config build-essential unzip zip

      - name: Warm up buildozer
        run: |
          buildozer android p4a -- version || true
          echo "Warmup done ✅"

      - name: Patch libffi recipe (disable autogen)
        run: |
          LIBFFI_PATH=".buildozer/android/platform/python-for-android/pythonforandroid/recipes/libffi/__init__.py"
          if [ -f "$LIBFFI_PATH" ]; then
            echo "Patching $LIBFFI_PATH..."
            # Comment out any autogen.sh or autoreconf calls
            sed -i 's/shprint.*autogen\.sh.*/print("Skip autogen.sh on CI")/g' "$LIBFFI_PATH"
            sed -i 's/shprint.*autoreconf.*/print("Skip autoreconf on CI")/g' "$LIBFFI_PATH"
            echo "✅ Patched libffi recipe successfully."
          else
            echo "⚠️ libffi recipe not found (maybe not downloaded yet)"
          fi

      - name: Build APK (debug)
        run: |
          buildozer android debug

      - name: Upload built APK
        uses: actions/upload-artifact@v4
        with:
          name: myapp-debug.apk
          path: bin/*-debug.apk
