name: Build Android APK

# Tự động chạy khi có push lên nhánh main
on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-24.04   # Chạy trên runner Ubuntu mới nhất (ổn định hơn)

    steps:
      # ================================
      # 1. Lấy mã nguồn về
      # ================================
      - name: Lấy code về (Checkout code)
        uses: actions/checkout@v4

      # ================================
      # 2. Thiết lập Java (bắt buộc cho Gradle/Android)
      # ================================
      - name: Thiết lập Java (Setup Java JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # ================================
      # 3. Thiết lập Python
      # (Python 3.10 hiện tương thích tốt nhất với Kivy/p4a)
      # ================================
      - name: Thiết lập Python (Setup Python 3.10)
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # ================================
      # 4. Cài đặt các gói hệ thống cần thiết
      # (Fix lỗi autoconf/libtool thiếu macro LT_SYS_SYMBOL_USCORE)
      # ================================
      - name: Cài đặt gói hệ thống bắt buộc (NDK/autoconf/libtool/zip)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake libtool \
            pkg-config build-essential cmake \
            zip unzip

      # ================================
      # 5. Cài đặt Buildozer, Python-for-Android, và Cython
      # ================================
      - name: Cài đặt Buildozer / python-for-android / Cython
        run: |
          python -m pip install --upgrade pip
          pip install "cython<3.1" buildozer python-for-android

      # ================================
      # 6. Build APK (debug)
      # ================================
      - name: Chạy Buildozer (Build APK debug)
        run: |
          buildozer -v android debug

      # ================================
      # 7. Tải file APK lên Artifact để tải về
      # ================================
      - name: Tải file APK lên (Upload Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-debug
          path: bin/*.apk
