name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-24.04

    steps:
      # 1. Checkout mã nguồn
      - name: Lấy code về (Checkout code)
        uses: actions/checkout@v4

      # 2. Setup Java (JDK 17 là chuẩn cho Gradle / Android hiện nay)
      - name: Thiết lập Java (Setup Java JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # 3. Setup Python (dùng 3.10 cho tương thích python-for-android ổn định hơn)
      - name: Thiết lập Python (Setup Python 3.10)
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 4. Cài các gói hệ thống cần cho biên dịch NDK, autoconf, libffi,...
      - name: Cài đặt gói hệ thống bắt buộc (NDK/autoconf/libtool/zip)
      # Bước này fix lỗi LT_SYS_SYMBOL_USCORE và các lỗi build C
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake libtool \
            pkg-config build-essential cmake \
            zip unzip \
            libncurses5 libtinfo5

      # 5. Cài buildozer + python-for-android + cython
      - name: Cài đặt Buildozer / python-for-android / Cython
        run: |
          python -m pip install --upgrade pip
          pip install "cython<3.1" buildozer python-for-android

      # 6. Build APK (debug)
      # Buildozer sẽ đọc file buildozer.spec trong repo của bạn
      - name: Chạy Buildozer (Build APK debug)
        run: |
          buildozer -v android debug

      # 7. Upload file APK ra Artifact để tải về
      - name: Tải file APK lên (Upload Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-debug
          path: bin/*.apk
