name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-24.04

    steps:
      # 1. Lấy code
      - name: Lấy code về (Checkout code)
        uses: actions/checkout@v4

      # 2. Java 17 cho Gradle / Android
      - name: Thiết lập Java (Setup Java JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # 3. Python (3.10 ổn định với python-for-android + Kivy)
      - name: Thiết lập Python (Setup Python 3.10)
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 4. Cài gói hệ thống cần cho toolchain C, libffi, autoconf/libtool
      - name: Cài đặt gói hệ thống bắt buộc (NDK/autoconf/libtool/zip)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake libtool libtool-bin \
            pkg-config build-essential cmake \
            zip unzip

      # 5. Cài buildozer + python-for-android + cython
      - name: Cài đặt Buildozer / python-for-android / Cython
        run: |
          python -m pip install --upgrade pip
          pip install "cython<3.1" buildozer python-for-android

      # 6. Build APK debug
      - name: Chạy Buildozer (Build APK debug)
        run: |
          buildozer -v android debug

      # 7. Upload file APK ra Artifact
      - name: Tải file APK lên (Upload Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-debug
          path: bin/*.apk
